// statics.js

export const jogosSerieB = [
  // Rodada 9 (existente)
  {
    rodada: 9,
    casa: 'Athletico-PR',
    fora: 'Athletic Club',
    local: 'Ligga Arena',
    resultado: '1 x 0',
    data: '24/05/2025',
    dia: 'Sábado',
    horario: '16:00',
  },
  {
    rodada: 9,
    casa: 'Goiás',
    fora: 'Ferroviária',
    local: 'Serrinha',
    resultado: '2 x 0',
    data: '24/05/2025',
    dia: 'Sábado',
    horario: '21:35',
  },
  {
    rodada: 9,
    casa: 'Cuiabá',
    fora: 'Vila Nova',
    local: 'Arena Pantanal',
    resultado: '1 x 0',
    data: '26/05/2025',
    dia: 'Segunda',
    horario: '21:00',
  },
  {
    rodada: 9,
    casa: 'Remo',
    fora: 'Volta Redonda',
    local: 'Mangueirão',
    resultado: '1 x 1',
    data: '24/05/2025',
    dia: 'Sábado',
    horario: '18:00',
  },
  {
    rodada: 9,
    casa: 'Avaí',
    fora: 'Chapecoense',
    local: 'Ressacada',
    resultado: '2 x 1',
    data: '24/05/2025',
    dia: 'Sábado',
    horario: '18:30',
  },
  {
    rodada: 9,
    casa: 'Criciúma',
    fora: 'Coritiba',
    local: 'Heriberto Hülse',
    resultado: '0 x 1',
    data: '26/05/2025',
    dia: 'Segunda',
    horario: '19:00',
  },
  {
    rodada: 9,
    casa: 'Amazonas',
    fora: 'Operário-PR',
    local: 'Carlos Zamith',
    resultado: '0 x 2',
    data: '25/05/2025',
    dia: 'Domingo',
    horario: '18:30',
  },
  {
    rodada: 9,
    casa: 'América-MG',
    fora: 'Atlético-GO',
    local: 'Independência',
    resultado: '2 x 1',
    data: '27/05/2025',
    dia: 'Terça',
    horario: '19:00',
  },
  {
    rodada: 9,
    casa: 'Novorizontino',
    fora: 'Paysandu',
    local: 'Jorge Ismael',
    resultado: '2 x 1',
    data: '25/05/2025',
    dia: 'Domingo',
    horario: '16:00',
  },
  {
    rodada: 9,
    casa: 'Botafogo-SP',
    fora: 'CRB',
    local: 'Arena Nicnet',
    resultado: '2x1',
    data: '26/05/2025',
    dia: 'Segunda',
    horario: '20:00',
  },

  // Rodada 10 (existente)
  {
    rodada: 10,
    casa: 'Coritiba',
    fora: 'Avaí',
    local: 'Couto Pereira',
    resultado: '2 x 1',
    data: '31/05/2025',
    dia: 'Sábado',
    horario: '16:00',
  },
  {
    rodada: 10,
    casa: 'Athletic Club',
    fora: 'Cuiabá',
    local: 'Independência',
    resultado: '0 x 2',
    data: '31/05/2025',
    dia: 'Sábado',
    horario: '20:30',
  },
  {
    rodada: 10,
    casa: 'Atlético-GO',
    fora: 'Goiás',
    local: 'Antônio Accioly',
    resultado: '1 x 2',
    data: '31/05/2025',
    dia: 'Sábado',
    horario: '18:30',
  },
  {
    rodada: 10,
    casa: 'Ferroviária',
    fora: 'Botafogo-SP',
    local: 'Fonte Luminosa',
    resultado: '1 x 1',
    data: '29/05/2025',
    dia: 'Quinta',
    horario: '21:35',
  },
  {
    rodada: 10,
    casa: 'Operário-PR',
    fora: 'Athletico-PR',
    local: 'Germano Krüger',
    resultado: '2 x 2',
    data: '01/06/2025',
    dia: 'Domingo',
    horario: '16:00',
  },
  {
    rodada: 10,
    casa: 'CRB',
    fora: 'Remo',
    local: 'Rei Pelé',
    resultado: '2 x 0',
    data: '01/06/2025',
    dia: 'Domingo',
    horario: '18:00',
  },
  {
    rodada: 10,
    casa: 'Volta Redonda',
    fora: 'América-MG',
    local: 'Raulino de Oliveira',
    resultado: '1 x 0',
    data: '01/06/2025',
    dia: 'Domingo',
    horario: '20:30',
  },
  {
    rodada: 10,
    casa: 'Vila Nova',
    fora: 'Novorizontino',
    local: 'Onésio Brasileiro Alvarenga (OBA)',
    resultado: '0 x 1',
    data: '30/06/2025',
    dia: 'Sexta',
    horario: '19:00',
  },
  {
    rodada: 10,
    casa: 'Paysandu',
    fora: 'Criciúma',
    local: 'Curuzu',
    resultado: '0 x 1',
    data: '02/06/2025',
    dia: 'Segunda',
    horario: '21:00',
  },
  {
    rodada: 10,
    casa: 'Chapecoense',
    fora: 'Amazonas',
    local: 'Arena Condá',
    resultado: '4 x 0',
    data: '02/06/2025',
    dia: 'Segunda',
    horario: '19:00',
  },


  {
    rodada: 11,
    casa: 'Botafogo-SP',
    fora: 'Coritiba',
    local: 'Arena Nicnet',
    resultado: '0 x 0',
    data: '05/06/2025',
    dia: 'Quinta',
    horario: '19:00',
  },
  {
    rodada: 11,
    casa: 'Novorizontino',
    fora: 'Chapecoense',
    local: 'Ligga Arena',
    resultado: '1 x 0',
    data: '06/06/2025',
    dia: 'Sexta',
    horario: '19:00',
  },
  {
    rodada: 11,
    casa: 'Cuiabá',
    fora: 'Paysandu',
    local: 'Arena Pantanal',
    resultado: '1 x 0',
    data: '06/06/2025',
    dia: 'Sexta',
    horario: '21:00',
  },
  {
    rodada: 11,
    casa: 'América-MG',
    fora: 'Ferroviária',
    local: 'Independência',
    resultado: '2 x 1',
    data: '07/06/2025',
    dia: 'Sábado',
    horario: '16:00',
  },
  {
    rodada: 11,
    casa: 'Avaí',
    fora: 'CRB',
    local: 'Ressacada',
    resultado: '1 x 0',
    data: '07/06/2025',
    dia: 'Sábado',
    horario: '20:30',
  },
  {
    rodada: 11,
    casa: 'Athletico-PR',
    fora: 'Atlético-GO',
    local: 'Ligga Arena',
    resultado: '0 x 1',
    data: '08/06/2025',
    dia: 'Domingo',
    horario: '18:00',
  },
  {
    rodada: 11,
    casa: 'Goiás',
    fora: 'Volta Redonda',
    local: 'Serrinha',
    resultado: '2 x 0',
    data: '08/06/2025',
    dia: 'Domingo',
    horario: '16:00',
  },
  {
    rodada: 11,
    casa: 'Remo',
    fora: 'Operário-PR',
    local: 'Mangueirão',
    resultado: '2 x 1',
    data: '08/06/2025',
    dia: 'Domingo',
    horario: '19:00',
  },
  {
    rodada: 11,
    casa: 'Novorizontino',
    fora: 'Chapecoense',
    local: 'Ligga Arena',
    resultado: '1 x 0',
    data: '06/06/2025',
    dia: 'Sexta',
    horario: '19:00',
  },  
  {
    rodada: 11,
    casa: 'Criciúma',
    fora: 'Vila Nova',
    local: 'Heriberto Hülse',
    resultado: 'Acontecerá',
    data: '09/06/2025',
    dia: 'Segunda',
    horario: '20:30',
  },
  {
    rodada: 11,
    casa: 'Amazonas',
    fora: 'Athletic Club',
    local: 'Carlos Zamith',
    resultado: 'Acontecerá',
    data: '09/06/2025',
    dia: 'Segunda',
    horario: '20:30',
  },
];
